serving:
  port: 8080
  halt-timeout: 60
anidb:
  index-url: "http://anidb.net/api/anime-titles.xml.gz"
  update-interval: 86400
  storage-dir: "anidb"
storage:
  key: "{{ .DO_SPACES_KEY }}"
  secret: "{{ .DO_SPACES_SECRET }}"
  host: "{{ .DO_SPACES_HOST }}"
  bucket: "{{ .DO_BUCKET }}"
  upload-timeout: 60
db:
  url: {{ if .PG_DB_URL }}"{{ .PG_DB_URL }}"{{ else }}"postgresql://postgres:postgres@localhost/postgres?sslmode=disable"{{ end }}
logging:
  profile: {{ if .ST_LOG }}"{{ .ST_LOG }}"{{ else }}"dev"{{ end }}
