// Code generated by sqlc. DO NOT EDIT.
// source: index_files.sql

package db

import (
	"context"
)

const addIndexFile = `-- name: AddIndexFile :exec
insert into anidb_index_files (name, hash)
values ($1, $2)
on conflict do nothing
`

type AddIndexFileParams struct {
	Name string `json:"name"`
	Hash string `json:"hash"`
}

// Adds new index file with given name and hash
// Does nothing if index file already exists
func (q *Queries) AddIndexFile(ctx context.Context, arg AddIndexFileParams) error {
	_, err := q.db.ExecContext(ctx, addIndexFile, arg.Name, arg.Hash)
	return err
}

const countIndexFiles = `-- name: CountIndexFiles :one
select count(*) from anidb_index_files
where name = $1
`

// Returns number of index files with given hash
func (q *Queries) CountIndexFiles(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIndexFiles, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}
